apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-setup
spec:
  selector:
    app: spring-cloud-setup
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31080