spring:
  application:
    name: spring-cloud-setup

management:
  endpoints:
    web:
      exposure:
        include: info, prometheus, metrics
  metrics:
    export:
      influx:
        db: db0
        uri: http://localhost:8086
        user-name: admin
        password: adminpassword
        step: 10s
        bucket: default
        token: GLfxENWXCTvQRknxpO9UTHu6KCxcrJBFb1e9eKWk6OOBqSpWjIlGuwmmVWq4wirMNa6CaWlwVEL4AJ6Nmr6qDw==
        org: default
    web:
      server:
        request:
          autotime:
            enabled: true

server:
  PORT: 8080

#influxClient:
#  INFLUX_URL: http://localhost:8086
#  INFLUX_DATABASE: db0
#  INFLUX_RETENTION_POLICY: autogen
#  INFLUX_ORGANIZATION: default
#  INFLUX_SEND_INTERVAL_MS: 10000
#  INFLUX_ACCESS_TOKEN: GLfxENWXCTvQRknxpO9UTHu6KCxcrJBFb1e9eKWk6OOBqSpWjIlGuwmmVWq4wirMNa6CaWlwVEL4AJ6Nmr6qDw==
#  INFLUX_BUCKET_ID: 8218b27d35b1d82d

#database:
#  DB_HOST: localhost
#  DB_PORT: 5432
#  DB_USERNAME: nodetest
#  DB_PASSWORD: nodetest
#  DB_DATABASE: nodetest

#logstash:
#  LOGSTASH_HOST: localhost
#  LOGSTASH_PORT: 5000
#  LOGSTASH_PROTOCOL: tcp

sqlite:
  DB_DATABASE: test.db.sqlite3

#subservice:
#  URL: http://localhost
#  PORT: 3001
